AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Api:
    Cors:
      AllowMethods: "'POST,OPTIONS'"
      AllowHeaders: "'Content-Type'"
      AllowOrigin: "'*'"

Resources:
  InterviewAPI:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda_function.lambda_handler
      Runtime: python3.10
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action: bedrock:InvokeModel
              Resource: '*'
      Events:
        Question:
          Type: Api
          Properties:
            Path: /question
            Method: post
        Evaluate:
          Type: Api
          Properties:
            Path: /evaluate
            Method: post

Outputs:
  ApiUrl:
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod'